### ISSUE TITLE
进入第二个页面返回数据无法接收

### ISSUE THREAD

**Issue by zj-wukewei** [listenzz/Live#3]
在第一个页面使用，
 Observable.create(new ObservableOnSubscribe<String>() {
            @Override
            public void subscribe(ObservableEmitter<String> e) throws Exception {
                Thread.sleep(3000);
                e.onNext("a");
                e.onComplete();
            }
        }).subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .compose(Live.bindLifecycle(this))
                .subscribe(it -> Log.d(TAG, it));
然后调用第二个页面，然后等待发送数据，之后无法接收到上游发送的数据，原因是调用了onComplete（）方法，导致considerNotify方法里面的!mDisposable.isDisposed()为false

**Comment by listenzz** [comment]
有什么解决建议或者提个 pr ?
